[project]
name = "fastapi-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "cryptography>=45.0.3",
    "fastapi[all]>=0.115.12",
    "uvicorn>=0.34.3",
]
